### ISSUE TITLE
Mutli file mod not working

### ISSUE THREAD

**Issue by FlockersDesign** [Abel-Gaming/FiveM-Script-Creator#1]
when using the multi file mod it is just using on of the 2 and you not able to use both menus only one and the other one get disabled
Alao with this way it wont let you compile multiple mods in one file for example a whant to make a pfull police function this had to be in 2 mods because its not allowing it in the same file structer

**Comment by Tyler-Abel** [comment]
The multi-file mod is to be used with two seperate .CS files. In your case, if you are attempting to make two seperate menus, please ensure two things
1) The namespace is the same for both menus
2) Please ensure that the public class does not have the same name (by default, this is what is on line 11 when you create a new menu, I have attached that below)
`public class MainMenu : BaseScript`

The "MainMenu" does have to be something else for the second menu

I will try and get around to creating a video showing how to create a mod with two seperate menus today or over the weekend at some point. I finally have some time off work that I can get some tutorials out!
