### ISSUE TITLE
Release Car is not working!!

### ISSUE THREAD

**Issue by FlockersDesign** [Abel-Gaming/FiveM-Script-Creator#2]
you can stop it but when you want to release the car it stays stopped

i hope you atleast react to this problem because aint looking like you react once a 4 weeks

**Comment by Tyler-Abel** [comment]
I'm not entirely sure what could be causing this issue, looking over my API functions; however, I updated them just in case there was an issue with the newest release of Script Creator. Please try with this new version, and if that doesn't fix it, please let me know and I will try to get to it as quick as possible!
