### ISSUE TITLE
Mod not compiling

### ISSUE THREAD

**Issue by JaspDevelopment** [Abel-Gaming/FiveM-Script-Creator#4]
When i try to compile the nativeui menu it doesnt compile the client.net.dll

**Comment by musictomy** [comment]
I had the same issue, same this was never kept updated etc.

Im going to learn visual and lua

**Comment by Tyler-Abel** [comment]
> When i try to compile the nativeui menu it doesnt compile the client.net.dll

Can you please provide your code?

**Comment by Tyler-Abel** [comment]
> I had the same issue, same this was never kept updated etc.
> 
> Im going to learn visual and lua

Please open a new topic and provide your code

**Comment by musictomy** [comment]
I found that windows defender was blocking some parts of the app, turn off defender and realtime and it saves it. (Turn off at your own risk, I did iut on a seperate install of windows.)

**Comment by Tyler-Abel** [comment]
> I found that windows defender was blocking some parts of the app, turn off defender and realtime and it saves it. (Turn off at your own risk, I did iut on a seperate install of windows.)

Perfect! Thank you for the update!
